// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wchjccnomfxjbqupnnvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjaGpjY25vbWZ4amJxdXBubnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NDMxMTIsImV4cCI6MjA3NjIxOTExMn0.4vqDALtLdlLePmgi3VDpy7qaE8rz1r2m2gG_c-T5ZTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);